language: generic
deploy:
  provider: s3
  access_key_id: AKIAJQ4ZVGWWETJZ5YPQ
  secret_access_key:
    secure: Pt98mICeiI3aW1EUTbGJKyaZlJMi6B3ziD3RomVnSQ7ZNlReIKF0YA5vcCQUx0nvu8sAnOuySg3gTxysoNOhx4l2dOYja6vRBNOcE7PErlptI41bhU9CGK7rMi1QQE+QP7JIY77wADCzEAKn3y4ksmIK16p7MPMpV1mTVo67RZ2CNxBZYcSuF8C+33QhdTvpwBHmmCpThIRYyf2+sBOdNVps+UcH/CDK+5YH5ZM20snsRQ07xQ8/T98mQbh259SSuXZ1aRc6QEACDJn14oCxT0m5unEhk1/WTubd6hyhUY79vPOeu/gjgCqA6O/wo83URddkZqP7dPOCnt/mKU9FfUzH6jXSQ7ns9HvV4eSzoqAPsJ336fnlJJ6N3sZ9KLyEoRweKkoKVNVrWRuNdq44pwqckMtsQXVWH/Xktesma3w+bxyWHTV2GbMr2wFGqcL5/cIGnkboTJB6yRNABWAklZP7API8l45llY4q7pR5zc8ZoDhT3GbzpDxcSUPyRcUta8ukIo4T0/FUctQsn3zU4M9EI5B+UXmt+VwUwQ3NJ/O7dOngXLmR/wPorAlbRKrDmm079dFfj1kLt6boXhUgMj4pj/b5QAMeHQ28VI3OHdEki94n6a2+bcbg9L//pX5t7IDJC4RgkAGj4whHDbsgnZsBMki+8VDX0K8YWgiS5CA=
  bucket: sylvanianfamilies.greenbearshire.com
  acl: bucket_owner_full_control
  on:
    repo: terrajackson/greenbearshire
